/* eslint-disable prettier/prettier */

import { TemplateFatura } from "../../../../interfaces/TemplateFatura";

export const jsoModelos1127926: TemplateFatura= { 
    fechaFactura:'04/02/2022',
    noFactura: "1127926",
    modelos:[
        {
            modelo:"ADO709UVLN/B/B-UVLN",
            tallas:[2]
        },        
        {
            modelo:"ADO709UVLN/B/NMC",
            tallas:[2]
        },
        {
            modelo:"SKY308CF/C/C-BPIRIG",
            tallas:[3]
        },
        {
            modelo:"SKY308UVG/C/NHPG",
            tallas:[2,3]
        },
        {
            modelo:"FLAM808UVLN/C/BGMPNK",
            tallas:[3]
        },
        {
            modelo:"PASN708/C/M",
            tallas:[3,4]
        },
        {
            modelo:"SKY308CP-1/C/B-SCH",
            tallas:[2]
        },
        {
            modelo:"MOON709CAT/B/B-S",
            tallas:[2,3]
        },
        {
            modelo:"ADO709SRS/B/NMC",
            tallas:[2]
        },
        {
            modelo:"ADO708T-2/SK-BPT/B-C",
            tallas:[2,3]
        },
        {
            modelo:"ADO708MG/C/M",
            tallas:[6]
        },
        {
            modelo:"MOON709UV/B/NMC",
            tallas:[3]
        },
        {
            modelo:"STDUS709/B/M",
            tallas:[3,4,5,6]
        },
        {
            modelo:"ADO708UV/C/NPN",
            tallas:[4,5,6]
        },
        {
            modelo:"ADO709UVLN/B/NMC",
            tallas:[2]
        },
        {
            modelo:"CYTL308PS/C/NHP",
            tallas:[3]
        },
        {
            modelo:"FLAM809SR/RPU/B-R",
            tallas:[3]
        },
        {   
            modelo:"FLAM809UVLN/B/N-UVLN",
            tallas:[3,4]
        },
        {
            modelo:"LOVESK712T/C-R/FDR",
            tallas:[2]
        },
        {
            modelo:"MOON760FH/B-R/B",
            tallas:[2,5]
        },
        {
            modelo:"SKY308G-T/C/BRGI",
            tallas:[3]
        },
        {
            modelo:"LOVESK712T/C-B/FDB",
            tallas:[4]
        },
        {
            modelo:"ADO701/C/B",
            tallas:[3,4,5,6]
        },
        {
            modelo:"ADO708RS-1/C/B",
            tallas:[3]
        },
        {
            modelo:"ADO708SP/C/SHG",
            tallas:[3]
        },
        {
            modelo:"ADO708VLRS/C/G",
            tallas:[3]
        },
        {
            modelo:"ADO709BR-H/B/B-R",
            tallas:[4,5]
        },
        {
            modelo:"ADO709LS/B/M",
            tallas:[4]
        },
        {
            modelo:"ADO709VLRS/SPU/M",
            tallas:[3]
        },
        {
            modelo:"ADO713/ND/M",
            tallas:[4]
        },
        {
            modelo:"FLAM808T/C/R",
            tallas:[4]
        },
        {
            modelo:"FLAM808SHAPE-2/C/S",
            tallas:[3]
        },
        {
            modelo:"FLAM808MC/C/LVHG",
            tallas:[3,4]
        },
        {
            modelo:"PASN708/C/M",
            tallas:[5,6]
        },
        {
            modelo:"SKY301T/C/SMK",
            tallas:[4]
        },
        {
            modelo:"STPLASH701/C/B",
            tallas:[2]
        },
        {
            modelo:"CYTL308PS/C/NHP",
            tallas:[2,3]
        },
        {
            modelo:"CYTL308PS/C/NTGR",
            tallas:[2,3]
        },
        {
            modelo:"FLAM801G/C/BG",
            tallas:[3]
        },
        {
            modelo:"FLAM801SRS/C/B",
            tallas:[3]
        },
        {
            modelo:"FLAM801/C/RCH",
            tallas:[3]
        },
        {
            modelo:"FLAM809UVLN/B/N-UVLN",
            tallas:[3,4]
        },
        {
            modelo:"ADO1020PK/BPU/M",
            tallas:[2]
        }
    ]
}

/* 
ADO709UVLN/B/NMC
ADO709UVLN/B/NMC
CYTL308PS/C/NHP
CYTL308PS/C/NHP
FLAM809UVLN/B/N-UVLN
FLAM809UVLN/B/N-UVLN
PASN708/C/M
PASN708/C/M
SKY301T/C/SMK
SKY308G-T/C/BRGI                
*/