/* eslint-disable prettier/prettier */

import { TemplateFatura } from "../../../../interfaces/TemplateFatura";

export const jsoModelos1114362: TemplateFatura= { 
    fechaFactura:'25/10/2021',
    noFactura: "1114362",
    modelos:[
        {
            modelo:"ADO3000HWR/WHG/M",
            tallas:[6]
        },
        
        {
            modelo:"ADO701/C/B",
            tallas:[2,4]
        },
        {
            modelo:"ADO701FL/C/HP",
            tallas:[3,5,6]
        },
        {
            modelo:"ADO701FL/C/R",
            tallas:[4]
        },
        {
            modelo:"ADO701SRS/C/B",
            tallas:[6]
        },
        {
            modelo:"ADO708CG/C/BG",
            tallas:[2]
        },
        {
            modelo:"ADO708CG/C/SG",
            tallas:[3,4]
        },
        {
            modelo:"ADO708SRS/C/NMC",
            tallas:[3,4]
        },
        {
            modelo:"ADO709/B/M",
            tallas:[3,4,5]
        },
        {
            modelo:"ADO709RC/B/RBOWCH",
            tallas:[3,4]
        },
        {
            modelo:"ADO709UVLN/B/NMC",
            tallas:[4,5]
        },
        {
            modelo:"CAP609/B/C",
            tallas:[5,6]
        },
        {
            modelo:"CLAS20/BLSA",
            tallas:[6]
        },
        {
            modelo:"CYTL308PS/C/NTGR",
            tallas:[3,4]
        },
        {
            modelo:"DEL600-17/BELS/M",
            tallas:[2,3]
        },
        {
            modelo:"DEL600-26/BPU/M",
            tallas:[3]
        },
        {
            modelo:"DEL634/BFS/M",
            tallas:[6,6]
        },
            {            modelo:"FLAM801T/C/SMK",
            tallas:[3]
        },
        {
            modelo:"FLAM808LN/C/B",
            tallas:[3]
        },
        {
            modelo:"FLAM808SHAPE-1/C/S",
            tallas:[3]
        },
        {
            modelo:"MOON701HRS/C/B-R",
            tallas:[2,3,4]
        },
        {
            modelo:"MOON708DIA/C/M",
            tallas:[4]
        },
        {
            modelo:"MOON708HRS/C/C-R",
            tallas:[3,4]
        },
        {
            modelo:"MOON708SK/C/B-PW",
            tallas:[3]
        },
        {
            modelo:"MOON709CAT/B/B-S",
            tallas:[2]
        },
        {
            modelo:"SCLP708-2RS/C/B-PWRS",
            tallas:[4,5]
        },
        {
            modelo:"SKY301T/C/SMK",
            tallas:[2,4]
        },
        {
            modelo:"SKY308T/C/SMK",
            tallas:[4,4]
        },
        {
            modelo:"SKY308UVMG/PNT/M",
            tallas:[2]
        },
        {
            modelo:"SKY308WHG/C/C-BPG",
            
            tallas:[2,3,4]
        },
        {
            modelo:"SKY309GPT/B/SMK",
            tallas:[3,3,4,4]
        },
        {
            modelo:"SKY309MG/B/M",
            tallas:[2,2,3,3,4,4,5,5,6]
        },
        {
            modelo:"SKY334/BFS/M",
            tallas:[3,3,4,4,5]
        },
        {
            modelo:"STPLASH701/C/B",
            tallas:[2]
        },
        {
            modelo:"TAB708MG/C/M",
            tallas:[3]
        },
        {
            modelo:"TIP708-5/C/BG",
            tallas:[4,5]
        },
        {
            modelo:"UNI708T/C/BGUMPN",
            tallas:[3]
        },
        {
            modelo:"UNI708T/C/BU",
            tallas:[4]
        }
    ]
}