/* eslint-disable prettier/prettier */
import { TemplateFatura } from "../../interfaces/TemplateFatura";

export const jsoModelos: Array<TemplateFatura> = [
        {
            "modelo":"ADO3000HWR/WHG/M",
            "tallas":[
                9
            ]
        },
        {
            "modelo":"ADO701/C/B",
            "tallas":[5,7]
        },
        {
            "modelo":"ADO701/C/B",
            "tallas":[5]
        },
        {
            "modelo":"ADO701FL/C/HP",
            "tallas":[6]
        },
        {
            "modelo":"ADO701FL/C/HP",
            "tallas":[8]
        },
        {
            "modelo":"ADO701FL/C/HP",
            "tallas":[9]
        },

        {
            "modelo":"ADO701FL/C/R",
            "tallas":[7]
        },
        {
            "modelo":"ADO701SRS/C/B",
            "tallas":[9]
        },
        {
            "modelo":"ADO708CG/C/BG",
            "tallas":[5]
        },
        {
            "modelo":"ADO708CG/C/SG",
            "tallas":[6]
        },
        {
            "modelo":"ADO708CG/C/SG",
            "tallas":[7]
        },
        {
            "modelo":"ADO708SRS/C/NMC",
            "tallas":[6]
        },
        {
            "modelo":"ADO708SRS/C/NMC",
            "tallas":[7]
        },
        {
            "modelo":"ADO709/B/M",
            "tallas":[6]
        },
        {
            "modelo":"ADO709/B/M",
            "tallas":[7]
        },
        {
            "modelo":"ADO709/B/M",
            "tallas":[8]
        },
        {
            "modelo":"ADO709RC/B/RBOWCH",
            "tallas":[6]
        },
        {
            "modelo":"ADO709RC/B/RBOWCH",
            "tallas":[7]
        },
        {
            "modelo":"ADO709UVLN/B/NMC",
            "tallas":[7]
        },
        {
            "modelo":"ADO709UVLN/B/NMC",
            "tallas":[8]
        },
        {
            "modelo":"CAP609/B/C",
            "tallas":[8]
        },
        {
            "modelo":"CAP609/B/C",
            "tallas":[9]
        },
        {
            "modelo":"CLAS20/BLSA",
            "tallas":[9]
        },
        {
            "modelo":"CYTL308PS/C/NTGR",
            "tallas":[6]
        },
        {
            "modelo":"DEL600-17/BELS/M",
            "tallas":[5]
        },
        {
            "modelo":"DEL600-17/BELS/M",
            "tallas":[6]
        },
        {
            "modelo":"DEL600-26/BPU/M",
            "tallas":[6]
        },
        {
            "modelo":"DEL634/BFS/M",
            "tallas":[9]
        },
        {
            "modelo":"DEL634/BFS/M",
            "tallas":[9]
        },
        {
            "modelo":"FLAM801T/C/SMK",
            "tallas":[6]
        },
        {
            "modelo":"FLAM808LN/C/B",
            "tallas":[6]
        },
        {
            "modelo":"FLAM808SHAPE-1/C/S",
            "tallas":[6]
        },
        {
            "modelo":"MOON701HRS/C/B-R",
            "tallas":[5]
        },
        {
            "modelo":"MOON701HRS/C/B-R",
            "tallas":[6]
        },
        {
            "modelo":"MOON701HRS/C/B-R",
            "tallas":[7]
        },
        {
            "modelo":"MOON708DIA/C/M",
            "tallas":[7]
        },
        {
            "modelo":"MOON708HRS/C/C-R",
            "tallas":[6]
        },
        {
            "modelo":"MOON708HRS/C/C-R",
            "tallas":[7]
        },
        {
            "modelo":"MOON708SK/C/B-PW",
            "tallas":[6]
        },
        {
            "modelo":"MOON709CAT/B/B-S",
            "tallas":[5]
        },
        {
            "modelo":"SCLP708-2RS/C/B-PWRS",
            "tallas":[7]
        },
        {
            "modelo":"SCLP708-2RS/C/B-PWRS",
            "tallas":[8]
        },
        {
            "modelo":"SKY301T/C/SMK",
            "tallas":[5]
        },
        {
            "modelo":"SKY301T/C/SMK",
            "tallas":[7]
        },
        {
            "modelo":"SKY308T/C/SMK",
            "tallas":[7]
        },
        {
            "modelo":"SKY308T/C/SMK",
            "tallas":[7]
        },
        {
            "modelo":"SKY308UVMG/PNT/M",
            "tallas":[5]
        },
        {
            "modelo":"SKY308WHG/C/C-BPG",
            
            "tallas":[5]
        },
        {
            "modelo":"SKY308WHG/C/C-BPG",
            
            "tallas":[6]
        },
        {
            "modelo":"SKY308WHG/C/C-BPG",
            
            "tallas":[7]
        },
        {
            "modelo":"SKY309GPT/B/SMK",
            "tallas":[6]
        },
        {
            "modelo":"SKY309GPT/B/SMK",
            "tallas":[7]
        },
        {
            "modelo":"SKY309GPT/B/SMK",
            "tallas":[6]
        },
        {
            "modelo":"SKY309GPT/B/SMK",
            "tallas":[7]
        },
        {
            "modelo":"SKY309MG/B/M",
            "tallas":[5]
        },
        {
            "modelo":"SKY309MG/B/M",
            "tallas":[5]
        },
        {
            "modelo":"SKY309MG/B/M",
            "tallas":[6]
        },
        {
            "modelo":"SKY309MG/B/M",
            "tallas":[6]
        },
        {
            "modelo":"SKY309MG/B/M",
            "tallas":[7]
        },
        {
            "modelo":"SKY309MG/B/M",
            "tallas":[7]
        },
        {
            "modelo":"SKY309MG/B/M",
            "tallas":[8]
        },
        {
            "modelo":"SKY309MG/B/M",
            "tallas":[8]
        },
        {
            "modelo":"SKY309MG/B/M",
            "tallas":[9]
        },
        {
            "modelo":"SKY334/BFS/M",
            "tallas":[6]
        },
        {
            "modelo":"SKY334/BFS/M",
            "tallas":[7]
        },
        {
            "modelo":"SKY334/BFS/M",
            "tallas":[8]
        },
        {
            "modelo":"SKY334/BFS/M",
            "tallas":[6]
        },
        {
            "modelo":"SKY334/BFS/M",
            "tallas":[7]
        },
        {
            "modelo":"STPLASH701/C/B",
            "tallas":[5]
        },
        {
            "modelo":"TAB708MG/C/M",
            "tallas":[6]
        },
        {
            "modelo":"TIP708-5/C/BG",
            "tallas":[7]
        },
        {
            "modelo":"TIP708-5/C/BG",
            "tallas":[8]
        },
        {
            "modelo":"UNI708T/C/BGUMPN",
            "tallas":[6]
        },
        {
            "modelo":"UNI708T/C/BU",
            "tallas":[7]
        }
        
    ];
    