/* eslint-disable prettier/prettier */
import { TemplateFatura } from "../../../../interfaces/TemplateFatura";

export const jsonBitacoraModelos: TemplateFatura = {
    fechaFactura: '01/09/2021',
    noFactura: "bita12345",
    modelos:[
        {
            "modelo":"ADO701UVL/C/B-NPN",
            "tallas":[
                2
            ]
        },
        {
            "modelo":"ADO709SRS/B/NMC",
            "tallas":[
                2,4
            ]
        },
        {
            "modelo":"ADO709WR/B/RBOWG",
            "tallas":[
                2,2,3,4
            ]
        },
        {
            "modelo":"CYTL308TL/C/PN",
            "tallas":[
                2,3,4
            ]
        },
        {
            "modelo":"SKY301-5/C/B-NW",
            "tallas":[
                2,3
            ]
        },
        {
            "modelo":"SKY309/B/M",
            "tallas":[
                2,2,3,4
            ]
        },
        {
            "modelo":"SKY309LNRS/B/M",
            "tallas":[
                2,3,6
            ]
        },
        {
            "modelo":"SKY309MG/B/M",
            "tallas":[
                2
            ]
        },
        {
            "modelo":"STDUS708/C/B",
            "tallas":[
                2,3
            ]
        },
        {
            "modelo":"ADO701/B/M",
            "tallas":[
                3,4
            ]
        },
        {
            "modelo":"ADO701LG/C/BLG",
            "tallas":[
                3
            ]
        },
        {
            "modelo":"ADO701SRS/C/B",
            "tallas":[
                3,5
            ]
        },
        {
            "modelo":"ADO708BR-H/C/B-R",
            "tallas":[
                3
            ]
        },
        {
            "modelo":"ADO708CHLN/C/ROGLDCH",
            "tallas":[
                3
            ]
        },
        {
            "modelo":"ADO708MCT/C/LBL",
            "tallas":[
                3
            ]
        },
        {
            "modelo":"ADO708MMG/C/M",
            "tallas":[
                3
            ]
        },
        {
            "modelo":"ADO708OMBRE/C/EM-B",
            "tallas":[
                3,4
            ]
        },
        {
            "modelo":"ADO708RSTG/C-B/C",
            "tallas":[
                3
            ]
        },
        {
            "modelo":"ADO709BR-H/B/B-R",
            "tallas":[
                3,6
            ]
        },
        {
            "modelo":"CYTL308PS/C/NGN",
            "tallas":[
                3
            ]
        },
        {
            "modelo":"CYTL308PS/C/NHP",
            "tallas":[
                3
            ]
        },
        {
            "modelo":"ESTM709BR/B/R-B",
            "tallas":[
                3,4
            ]
        },
        {
            "modelo":"FLAM809UVLN/B/N-UVLN",
            "tallas":[
                3
            ]
        },
        {
            "modelo":"FDANCE702CH/C/SHG",
            "tallas":[
                3
            ]
        },
        {
            "modelo":"LOVEHN708CRS/C/B",
            "tallas":[
                3
            ]
        },
        {
            "modelo":"MOON708/C/B",
            "tallas":[
                3
            ]
        },
        {
            "modelo":"MOON708GFT/C/PN",
            "tallas":[
                3
            ]
        },
        {
            "modelo":"MOON708MG/C/M",
            "tallas":[
                3
            ]
        },
        {
            "modelo":"RBOW309UV/B/NMC",
            "tallas":[
                3
            ]
        },
        {
            "modelo":"SKY301/C-B/C",
            "tallas":[
                3,4,5
            ]
        },
        {
            "modelo":"SKY301-5/C/B-NHP",
            "tallas":[
                3,6
            ]
        },
        {
            "modelo":"SKY301T/C/SMK",
            "tallas":[
                3,5
            ]
        },
        {
            "modelo":"SKY302SRS/C/B",
            "tallas":[
                3,4,5
            ]
        },
        {
            "modelo":"SKY302SRS/C/S",
            "tallas":[
                3
            ]
        },
        {
            "modelo":"SKY308CF/C/C-BPIRIG",
            "tallas":[
                3,5
            ]
        },
        {
            "modelo":"SKY308CP-1/C/B-SCH",
            "tallas":[
                3,3
            ]
        },
        {
            "modelo":"SKY308LN/C/B",
            "tallas":[
                3
            ]
        },
        {
            "modelo":"SKY308OF/C/S",
            "tallas":[
                3
            ]
        },
        {
            "modelo":"SKY308T/C/SMK",
            "tallas":[
                3,4,5
            ]
        },
        {
            "modelo":"SKY308WHG/C/B-RG",
            "tallas":[
                3,4,5
            ]
        },
        {
            "modelo":"STDANCE708/C/B",
            "tallas":[
                3
            ]
        },
        {
            "modelo":"STDUS702T/C/HP-C",
            "tallas":[
                3
            ]
        },
        {
            "modelo":"STDUS702T/C/PP-C",
            "tallas":[
                3,4
            ]
        },
        {
            "modelo":"STDUS708T/C/B-C",
            "tallas":[
                3
            ]
        },
        {
            "modelo":"STDUS708T/C/PP-C",
            "tallas":[
                3
            ]
        },
        {
            "modelo":"STPLASH701/C/B",
            "tallas":[
                3
            ]
        },
        {
            "modelo":"ADO701LN/C/B",
            "tallas":[
                4,5
            ]
        },
        {
            "modelo":"ADO708-2HGM/C/ROGHG",
            "tallas":[
                4
            ]
        },
        {
            "modelo":"ADO708STORM/C/PNHG",
            "tallas":[
                4
            ]
        },
        {
            "modelo":"ADO708T-2/SK-BPT/B-C",
            "tallas":[
                4,5
            ]
        },
        {
            "modelo":"ADO708T/C/R",
            "tallas":[
                4
            ]
        },
        {
            "modelo":"ADO708UVLN/C/B-NMC",
            "tallas":[
                4
            ]
        },
        {
            "modelo":"ADO709/B/M",
            "tallas":[
                4
            ]
        },
        {
            "modelo":"ADO714/BPT-RELS/B",
            "tallas":[
                4,5
            ]
        },
        {
            "modelo":"MOON701TG/C/B-S",
            "tallas":[
                4
            ]
        },
        {
            "modelo":"RAPT808/C/M",
            "tallas":[
                4
            ]
        },
        {
            "modelo":"SKY308GF/C/TURG",
            "tallas":[
                4
            ]
        },
        {
            "modelo":"ADO701-3/C/B-PW",
            "tallas":[
                5
            ]
        },
        {
            "modelo":"ADO701/C/B",
            "tallas":[
                5
            ]
        },
        {
            "modelo":"ADO709LS/B/M",
            "tallas":[
                5,6
            ]
        },
        {
            "modelo":"ADO709SP/RSPPT/B",
            "tallas":[
                5
            ]
        },
        {
            "modelo":"ADO709T/B/R",
            "tallas":[
                5
            ]
        },
        {
            "modelo":"ADO102OBR-H/B/B-R",
            "tallas":[
                5
            ]
        },
        {
            "modelo":"FDANCE708SCHSQ/C/CSQ",
            "tallas":[
                5
            ]
        },
        {
            "modelo":"KNUCKS709/B/M",
            "tallas":[
                5,6
            ]
        },
        {
            "modelo":"SKY302SRS/C/NMC",
            "tallas":[
                5
            ]
        },
        {
            "modelo":"SKY308CP-3/C/B-SCH",
            "tallas":[
                5
            ]
        },
        {
            "modelo":"SKY310SQ/B/PWCH",
            "tallas":[
                5
            ]
        },
        {
            "modelo":"SKY334/BFS/M",
            "tallas":[
                5
            ]
        },
        {
            "modelo":"STDUS708/C/M",
            "tallas":[
                5
            ]
        },

        {
            "modelo":"ASP609/B/C",
            "tallas":[
                6
            ]
        },
        {
            "modelo":"DEL601/B/M",
            "tallas":[
                6
            ]
        },
        {
            "modelo":"DEL609/B/M",
            "tallas":[
                6,6
            ]
        }
    ]
}