/* eslint-disable prettier/prettier */

import { TemplateFatura } from "../../../../interfaces/TemplateFatura";

export const jsoModelos1127926: TemplateFatura= { 
    fechaFactura:'25/03/2022',
    noFactura: "1135202",
    modelos:[
        {
            modelo:"SKY309/B/M",
            tallas:[2,3,4,5]
        },        
        {
            modelo:"SKY308WHG/C/C-BPG",
            tallas:[3]
        },
        {
            modelo:"SKY308MC/C/LVHG",
            tallas:[2,3,4,5,6]
        },
        {
            modelo:"SKY301T/C/SMK",
            tallas:[4,4,4]
        },
        {
            modelo:"MOON708MER/C/B",
            tallas:[2,3]
        },
        {
            modelo:"MOON708MER/C/M",
            tallas:[2,3]
        },
        {
            modelo:"MOON701HRS/C/B-R",
            tallas:[4,5,6]
        },
        {
            modelo:"MOON708DIA/C/M",
            tallas:[3,6]
        },
        {
            modelo:"ADO708RS-1/C/B",
            tallas:[2]
        },
        {
            modelo:"STDUS702/C/M",
            tallas:[3,4,5,6]
        },
        {
            modelo:"ESTM709/B/C-B",
            tallas:[3,4,5]
        },
        {
            modelo:"MOON701/C/M",
            tallas:[2]
        },
        {
            modelo:"MOON708UV/C/NMC",
            tallas:[2,3]
        },
        {
            modelo:"SKY308LN/C/B",
            tallas:[3]
        },
        {
            modelo:"SKY309LN/B/M",
            tallas:[5]
        },
        {
            modelo:"ADO709UVLN/B/B-UVLN",
            tallas:[4]
        },
        {
            modelo:"ADO708CG/C/BG",
            tallas:[4,5,6]
        },
        {   
            modelo:"ADO708CG/C/SG",
            tallas:[4,5,6]
        },
        {
            modelo:"ADO708HGI/C/PN",
            tallas:[3]
        },
        {
            modelo:"TAB701/C/M",
            tallas:[3,4]
        },
        {
            modelo:"OLIVE08/BPU",
            tallas:[6]
        },
        {
            modelo:"OLIVE08/BPPU",
            tallas:[6,6]
        },
        {
            modelo:"SKY309/B/C",
            tallas:[3,4,5,6]
        },
        {
            modelo:"ASP608STD/C/B-C",
            tallas:[4,5,6]
        },
        {
            modelo:"ADO709UVLN/B/NMC",
            tallas:[4,4,4]
        },
        {
            modelo:"ADO709BR-H/B/B-R",
            tallas:[6]
        },
        {
            modelo:"KISS209/B/LE",
            tallas:[4]
        },
        {
            modelo:"SKY308/C-B/M",
            tallas:[4]
        },
        {
            modelo:"ADO701/B/M",
            tallas:[5,6]
        },
        {
            modelo:"ADO710G/OPG/M",
            tallas:[5,6]
        },
        {
            modelo:"OLIVE08/AQPU",
            tallas:[6,6]
        },
        {
            modelo:"SKY308CF/C/C-BPIRIG",
            tallas:[3]
        },
        {
            modelo:"SKY309HG/ROGLDHG/B",
            tallas:[3]
        },
        {
            modelo:"DEL3025/BPU/M",
            tallas:[2]
        },
        
    ]
}